// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UniqueFileId {
    #[prost(string, tag = "1")]
    pub md5: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sha256: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub collision_id: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileToDownload {
    #[prost(message, optional, tag = "1")]
    pub file_id: ::core::option::Option<UniqueFileId>,
    #[prost(string, tag = "2")]
    pub current_md5: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub current_sha256: ::prost::alloc::string::String,
    /// usize mapped to uint64 for safety
    #[prost(uint64, tag = "4")]
    pub current_size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileOk {
    #[prost(message, optional, tag = "1")]
    pub file_id: ::core::option::Option<UniqueFileId>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerMessage {
    #[prost(oneof = "server_message::Kind", tags = "1, 2")]
    pub kind: ::core::option::Option<server_message::Kind>,
}
/// Nested message and enum types in `ServerMessage`.
pub mod server_message {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        FileToDownload(super::FileToDownload),
        #[prost(message, tag = "2")]
        FileOk(super::FileOk),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewFileId {
    #[prost(message, optional, tag = "1")]
    pub file_id: ::core::option::Option<UniqueFileId>,
    #[prost(uint64, tag = "2")]
    pub size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileToDownloadInvalid {
    #[prost(message, optional, tag = "1")]
    pub file_id: ::core::option::Option<UniqueFileId>,
    #[prost(string, tag = "2")]
    pub current_md5: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub current_sha256: ::prost::alloc::string::String,
    /// usize mapped to uint64 for safety
    #[prost(uint64, tag = "4")]
    pub current_size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileChunk {
    #[prost(message, optional, tag = "1")]
    pub file_id: ::core::option::Option<UniqueFileId>,
    #[prost(uint64, tag = "2")]
    pub size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMessage {
    #[prost(oneof = "client_message::Kind", tags = "1")]
    pub kind: ::core::option::Option<client_message::Kind>,
}
/// Nested message and enum types in `ClientMessage`.
pub mod client_message {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        FileToDownload(super::FileToDownload),
    }
}
